repos:
  - repo: local
    hooks:
      - id: scalafmt
        name: Scalafmt
        entry: sbtx scalafmtCheckAll
        language: system
        pass_filenames: false
        files: '.*\.scala$'

      - id: scalafix
        name: Scalafix
        entry: sbtx "scalafixAll --check"
        language: system
        pass_filenames: false
        files: '.*\.scala$'