repos:
  - repo: local
    hooks:
      - id: scalafmt
        name: Scalafmt
        entry: ./sbt.bat scalafmtCheckAll
        language: system
        pass_filenames: false
        types: [ scala ]
        always_run: true
        verbose: true

      - id: scalafix
        name: Scalafix
        entry: ./sbt.bat "scalafixAll --check"
        language: system
        pass_filenames: false
        types: [ scala ]
        always_run: true
        verbose: true