version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_keyla
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: profiles_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/profiles_db --quiet --username admin --password admin
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: